package com.kamyabpakhsh.staff;

import android.app.*;import android.os.*;import android.graphics.Color;import android.graphics.Typeface;import android.text.InputType;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import android.graphics.drawable.GradientDrawable;

public class MainActivity extends Activity {
 int green=Color.rgb(0,168,107), dark=Color.rgb(7,26,20), soft=Color.rgb(238,247,243); LinearLayout root;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(dark);showLogin();}
 TextView text(String s,int sp){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(Color.WHITE);v.setGravity(Gravity.CENTER);v.setPadding(12,12,12,12);return v;}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER_HORIZONTAL);root.setPadding(28,24,28,24);root.setBackgroundColor(dark);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);}
 void showLogin(){base();Space top=new Space(this);root.addView(top,new LinearLayout.LayoutParams(1,18));ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(logo,new LinearLayout.LayoutParams(-1,220));TextView title=text("کامیاب پخش",27);title.setTypeface(null,Typeface.BOLD);root.addView(title);TextView sub=text("سامانه داخلی مدیریت و پرسنل",15);sub.setTextColor(Color.LTGRAY);root.addView(sub);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(24,24,24,24);card.setBackground(bg(Color.WHITE,28));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,25,0,0);root.addView(card,cp);TextView loginTitle=text("ورود به حساب کاربری",19);loginTitle.setTextColor(dark);loginTitle.setTypeface(null,Typeface.BOLD);card.addView(loginTitle);EditText u=input("نام کاربری",false),p=input("رمز عبور",true);card.addView(u);card.addView(p);p.setImeOptions(EditorInfo.IME_ACTION_DONE);CheckBox show=new CheckBox(this);show.setText("نمایش رمز عبور");show.setTextColor(Color.DKGRAY);show.setOnCheckedChangeListener((b,c)->{int pos=p.getSelectionStart();p.setInputType(InputType.TYPE_CLASS_TEXT|(c?InputType.TYPE_TEXT_VARIATION_VISIBLE_PASSWORD:InputType.TYPE_TEXT_VARIATION_PASSWORD));p.setSelection(Math.max(0,pos));});card.addView(show);Button login=new Button(this);login.setText("ورود به سامانه");login.setTextSize(18);login.setTextColor(Color.WHITE);login.setBackground(bg(green,24));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,125);lp.setMargins(0,16,0,0);card.addView(login,lp);View.OnClickListener go=v->{String us=u.getText().toString().trim(),pw=p.getText().toString();if(us.isEmpty()||pw.isEmpty()){Toast.makeText(this,"نام کاربری و رمز عبور را وارد کنید",Toast.LENGTH_SHORT).show();}else if(us.equals("admin")&&pw.equals("1234")){showDashboard();}else{Toast.makeText(this,"نام کاربری یا رمز عبور اشتباه است",Toast.LENGTH_SHORT).show();}};login.setOnClickListener(go);p.setOnEditorActionListener((v,a,e)->{if(a==EditorInfo.IME_ACTION_DONE){login.performClick();return true;}return false;});TextView foot=text("نسخه ۱.۲  •  حسمان تجارت کامیاب",12);foot.setTextColor(Color.GRAY);root.addView(foot);}
 EditText input(String hint,boolean pass){EditText e=new EditText(this);e.setHint(hint);e.setSingleLine(true);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.GRAY);e.setTextDirection(View.TEXT_DIRECTION_RTL);e.setPadding(25,0,25,0);e.setBackground(bg(soft,20));if(pass)e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,115);lp.setMargins(0,14,0,0);e.setLayoutParams(lp);return e;}
 void showDashboard(){base();LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=text("داشبورد مدیریت",23);h.setTypeface(null,Typeface.BOLD);head.addView(h,new LinearLayout.LayoutParams(0,80,1));Button out=new Button(this);out.setText("خروج");out.setTextColor(dark);out.setBackground(bg(Color.WHITE,18));out.setOnClickListener(v->showLogin());head.addView(out,new LinearLayout.LayoutParams(190,80));root.addView(head,new LinearLayout.LayoutParams(-1,-2));TextView welcome=text("سلام مدیر 👋\nدسترسی سریع به بخش‌های کاری کامیاب پخش",15);welcome.setGravity(Gravity.RIGHT);welcome.setTextColor(Color.LTGRAY);root.addView(welcome,new LinearLayout.LayoutParams(-1,-2));String[] items={"👥\nمدیریت پرسنل","📝\nگزارش روزانه","🛒\nثبت سفارش","💰\nپیگیری مطالبات","📦\nمدیریت انبار","🚚\nتحویل و توزیع","📊\nگزارش‌های مدیریتی","⏰\nحضور و غیاب","🔔\nپیام‌ها و اعلان‌ها"};GridLayout grid=new GridLayout(this);grid.setColumnCount(2);grid.setAlignmentMode(GridLayout.ALIGN_BOUNDS);for(String s:items){TextView c=text(s,16);c.setTypeface(null,Typeface.BOLD);c.setTextColor(dark);c.setGravity(Gravity.CENTER);c.setBackground(bg(Color.WHITE,25));c.setOnClickListener(v->Toast.makeText(this,((TextView)v).getText().toString().replace("\n"," ")+" به‌زودی فعال می‌شود",Toast.LENGTH_SHORT).show());GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=170;gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);gp.setMargins(8,8,8,8);grid.addView(c,gp);}ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(grid);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));}
 @Override public void onBackPressed(){new AlertDialog.Builder(this).setMessage("می‌خواهید از برنامه خارج شوید؟").setNegativeButton("خیر",null).setPositiveButton("بله",(d,w)->finish()).show();}
}
