package com.kamyabpakhsh.staff;
import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.Typeface;import android.text.InputType;import android.view.*;import android.view.inputmethod.EditorInfo;import android.widget.*;import android.graphics.drawable.GradientDrawable;import android.content.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity{
 int green=Color.rgb(0,168,107),dark=Color.rgb(7,26,20),soft=Color.rgb(238,247,243); LinearLayout root; SharedPreferences db; String current="admin";
 @Override public void onCreate(Bundle b){super.onCreate(b);db=getSharedPreferences("kamyab",MODE_PRIVATE);getWindow().setStatusBarColor(dark);showLogin();}
 GradientDrawable bg(int c,int r){GradientDrawable g=new GradientDrawable();g.setColor(c);g.setCornerRadius(r);return g;}
 TextView txt(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setGravity(Gravity.RIGHT|Gravity.CENTER_VERTICAL);v.setPadding(18,12,18,12);return v;}
 void base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(24,20,24,20);root.setBackgroundColor(dark);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);setContentView(root);}
 EditText in(String h,boolean pass){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.GRAY);e.setPadding(22,0,22,0);e.setBackground(bg(soft,20));if(pass)e.setInputType(129);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,110);p.setMargins(0,10,0,0);e.setLayoutParams(p);return e;}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextSize(16);b.setTextColor(Color.WHITE);b.setBackground(bg(green,20));return b;}
 void showLogin(){base();ImageView logo=new ImageView(this);logo.setImageResource(R.drawable.logo);logo.setScaleType(ImageView.ScaleType.CENTER_INSIDE);root.addView(logo,new LinearLayout.LayoutParams(-1,210));TextView t=txt("کامیاب پخش",28,Color.WHITE);t.setGravity(Gravity.CENTER);t.setTypeface(null,Typeface.BOLD);root.addView(t);TextView s=txt("سامانه یکپارچه پرسنل",15,Color.LTGRAY);s.setGravity(Gravity.CENTER);root.addView(s);LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(22,22,22,22);card.setBackground(bg(Color.WHITE,28));root.addView(card,new LinearLayout.LayoutParams(-1,-2));EditText u=in("نام کاربری",false),p=in("رمز عبور",true);card.addView(u);card.addView(p);CheckBox sh=new CheckBox(this);sh.setText("نمایش رمز عبور");sh.setTextColor(Color.DKGRAY);sh.setOnCheckedChangeListener((x,c)->p.setInputType(c?145:129));card.addView(sh);Button login=btn("ورود به سامانه");card.addView(login,new LinearLayout.LayoutParams(-1,115));login.setOnClickListener(v->{String us=u.getText().toString().trim(),pw=p.getText().toString();boolean ok=us.equals("admin")&&pw.equals("1234");if(!ok)ok=db.getString("pass_"+us,"").equals(pw)&&!pw.isEmpty();if(ok){current=us;showDashboard();}else Toast.makeText(this,"نام کاربری یا رمز عبور اشتباه است",0).show();});root.addView(txt("نسخه ۲.۰ • حسمان تجارت کامیاب",12,Color.GRAY));}
 void header(String title){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);Button back=btn("‹ بازگشت");back.setOnClickListener(v->showDashboard());h.addView(back,new LinearLayout.LayoutParams(190,80));TextView tt=txt(title,22,Color.WHITE);tt.setTypeface(null,Typeface.BOLD);h.addView(tt,new LinearLayout.LayoutParams(0,80,1));root.addView(h);}
 void showDashboard(){base();TextView h=txt("داشبورد کامیاب پخش",24,Color.WHITE);h.setTypeface(null,Typeface.BOLD);root.addView(h);root.addView(txt("کاربر: "+current+"  •  "+new SimpleDateFormat("yyyy/MM/dd",Locale.US).format(new Date()),14,Color.LTGRAY));String[] a={"👥 مدیریت پرسنل","📝 گزارش روزانه","🛒 ثبت سفارش","💰 پیگیری مطالبات","📦 مدیریت انبار","🚚 تحویل و توزیع","📊 گزارش‌های مدیریتی","⏰ حضور و غیاب","🔔 پیام‌ها و اعلان‌ها"};GridLayout g=new GridLayout(this);g.setColumnCount(2);for(int i=0;i<a.length;i++){final int n=i;TextView c=txt(a[i],16,dark);c.setGravity(Gravity.CENTER);c.setTypeface(null,Typeface.BOLD);c.setBackground(bg(Color.WHITE,24));c.setOnClickListener(v->open(n));GridLayout.LayoutParams q=new GridLayout.LayoutParams();q.width=0;q.height=160;q.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1f);q.setMargins(7,7,7,7);g.addView(c,q);}ScrollView sc=new ScrollView(this);sc.addView(g);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));Button o=btn("خروج از حساب");o.setOnClickListener(v->showLogin());root.addView(o,new LinearLayout.LayoutParams(-1,95));}
 void open(int n){if(n==0)staff();else if(n==1)form("گزارش روزانه","شرح فعالیت امروز","ثبت گزارش","reports");else if(n==2)order();else if(n==3)form("پیگیری مطالبات","نام مشتری | مبلغ | توضیحات","ثبت پیگیری","debts");else if(n==4)form("مدیریت انبار","نام کالا | تعداد ورود/خروج | توضیحات","ثبت گردش انبار","stock");else if(n==5)form("تحویل و توزیع","شماره فاکتور | مشتری | وضعیت تحویل/وصول","ثبت تحویل","delivery");else if(n==6)reports();else if(n==7)attendance();else form("پیام‌ها و اعلان‌ها","متن پیام یا یادداشت مهم","ثبت پیام","messages");}
 void form(String title,String hint,String action,String key){base();header(title);EditText e=new EditText(this);e.setHint(hint);e.setGravity(Gravity.TOP|Gravity.RIGHT);e.setMinLines(7);e.setTextColor(Color.DKGRAY);e.setHintTextColor(Color.GRAY);e.setPadding(20,20,20,20);e.setBackground(bg(Color.WHITE,20));root.addView(e,new LinearLayout.LayoutParams(-1,0,1));Button b=btn(action);root.addView(b,new LinearLayout.LayoutParams(-1,105));b.setOnClickListener(v->{String x=e.getText().toString().trim();if(x.isEmpty()){Toast.makeText(this,"اطلاعات را وارد کنید",0).show();return;}save(key,x);e.setText("");Toast.makeText(this,"با موفقیت ثبت شد",0).show();});}
 void save(String key,String value){String old=db.getString(key,"");String now=new SimpleDateFormat("yyyy/MM/dd HH:mm",Locale.US).format(new Date());db.edit().putString(key,"["+now+"] "+current+": "+value+"\n"+old).apply();}
 void staff(){base();header("مدیریت پرسنل");if(!current.equals("admin")){root.addView(txt("این بخش فقط برای مدیر قابل دسترسی است.",17,Color.WHITE));return;}EditText name=in("نام و نام خانوادگی",false),user=in("نام کاربری جدید",false),pass=in("رمز عبور",false);root.addView(name);root.addView(user);root.addView(pass);Spinner role=new Spinner(this);String[] roles={"ویزیتور","تحویل‌دهنده","حسابدار / صندوقدار","انباردار","راننده","مدیر"};role.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,roles));root.addView(role);Button add=btn("ایجاد حساب پرسنل");root.addView(add,new LinearLayout.LayoutParams(-1,105));TextView list=txt("حساب‌های ثبت‌شده:\n"+db.getString("staff_list","هنوز حسابی ثبت نشده است."),15,Color.WHITE);root.addView(list);add.setOnClickListener(v->{String u=user.getText().toString().trim(),p=pass.getText().toString(),nm=name.getText().toString().trim();if(u.isEmpty()||p.isEmpty()||nm.isEmpty()){Toast.makeText(this,"همه فیلدها را کامل کنید",0).show();return;}db.edit().putString("pass_"+u,p).putString("role_"+u,role.getSelectedItem().toString()).putString("staff_list",nm+" — "+u+" — "+role.getSelectedItem()+"\n"+db.getString("staff_list","")).apply();Toast.makeText(this,"حساب پرسنل ساخته شد",0).show();staff();});}
 void order(){base();header("ثبت سفارش");EditText customer=in("نام مشتری",false),amount=in("مبلغ سفارش",false);amount.setInputType(2);root.addView(customer);root.addView(amount);EditText items=new EditText(this);items.setHint("کالاها، تعداد و توضیحات سفارش");items.setMinLines(5);items.setGravity(Gravity.TOP|Gravity.RIGHT);items.setBackground(bg(Color.WHITE,20));items.setPadding(20,20,20,20);root.addView(items,new LinearLayout.LayoutParams(-1,0,1));Button b=btn("ثبت سفارش");root.addView(b,new LinearLayout.LayoutParams(-1,105));b.setOnClickListener(v->{if(customer.getText().toString().trim().isEmpty()){Toast.makeText(this,"نام مشتری را وارد کنید",0).show();return;}save("orders",customer.getText()+" | مبلغ: "+amount.getText()+" | "+items.getText());Toast.makeText(this,"سفارش ثبت شد",0).show();customer.setText("");amount.setText("");items.setText("");});}
 void attendance(){base();header("حضور و غیاب");root.addView(txt("ثبت زمان شروع و پایان کار",18,Color.WHITE));Button in=btn("ثبت ورود");Button out=btn("ثبت خروج");LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,110);p.setMargins(0,15,0,0);root.addView(in,p);root.addView(out,p);TextView last=txt("آخرین وضعیت:\n"+db.getString("att_"+current,"ثبت نشده"),16,Color.WHITE);root.addView(last);in.setOnClickListener(v->att("ورود"));out.setOnClickListener(v->att("خروج"));}
 void att(String type){String t=type+" — "+new SimpleDateFormat("yyyy/MM/dd HH:mm:ss",Locale.US).format(new Date());db.edit().putString("att_"+current,t).apply();save("attendance",t);Toast.makeText(this,t,0).show();attendance();}
 void reports(){base();header("گزارش‌های مدیریتی");if(!current.equals("admin")){root.addView(txt("این بخش فقط برای مدیر قابل دسترسی است.",17,Color.WHITE));return;}ScrollView s=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);String[] k={"reports","orders","debts","stock","delivery","attendance","messages"};String[] n={"گزارش روزانه","سفارش‌ها","مطالبات","انبار","تحویل و توزیع","حضور و غیاب","پیام‌ها"};for(int i=0;i<k.length;i++){TextView h=txt("● "+n[i],18,green);h.setTypeface(null,Typeface.BOLD);box.addView(h);box.addView(txt(db.getString(k[i],"موردی ثبت نشده است."),14,Color.WHITE));}s.addView(box);root.addView(s,new LinearLayout.LayoutParams(-1,0,1));}
 @Override public void onBackPressed(){new AlertDialog.Builder(this).setMessage("می‌خواهید از برنامه خارج شوید؟").setNegativeButton("خیر",null).setPositiveButton("بله",(d,w)->finish()).show();}
}
